[language]
name = "nodejs"
version = "18"

[build]
command = """
cd client && npm install && npm run build && cd .. && \
cd server && npm install && npm run build && cd .. && \
mkdir -p /home/site/wwwroot/client && \
cp -r client/dist/* /home/site/wwwroot/client/
"""