# oryx.toml configuration for Node.js application on Azure App Service
[language]
name = "nodejs"
version = "18"

[build]
command = """
chmod +x ./deploy.sh && 
./deploy.sh
"""

# Indicate where the application's output is created
outputLocation = "server/dist"

# Set the startup command
run.command = "node server/dist/index.js"