[language]
name = "nodejs"
version = "18"

[build]
command = """
# Build client
cd client && npm install && npm run build && cd .. && \

# Build server
cd server && npm install && npm run build && \
cp -r dist /home/site/wwwroot/ && \
cp web.config /home/site/wwwroot/ && \
cp -r migrations /home/site/wwwroot/ && \
cp production.env /home/site/wwwroot/ && \
cp package.json /home/site/wwwroot/ && \
cd /home/site/wwwroot && npm install --production && cd /tmp/build && \

# Copy client build to wwwroot
mkdir -p /home/site/wwwroot/client && \
cp -r client/dist/* /home/site/wwwroot/client/
"""